### ISSUE TITLE
successfully connected but unable to get data from erpnext 

### ISSUE THREAD

**Issue by MdAlAmin-aol** [frappe/push-biometric-erpnext#3]
[error.log](https://github.com/frappe/push-biometric-erpnext/files/3921658/error.log)
[logs.log](https://github.com/frappe/push-biometric-erpnext/files/3921659/logs.log)

**Comment by karthikeyan5** [comment]
@MdAlAmin-aol , good that you have shared the logs... 

I think adding 'https' instead of 'http' for your erpnext instance URL should solve your issue.

https://stackoverflow.com/questions/28557466/python-requests-exception-connectionerror-connection-aborted-badstatusline

**Comment by MdAlAmin-aol** [comment]
thank you for quick respond.can you help me on this please.
[error.log](https://github.com/frappe/push-biometric-erpnext/files/3925793/error.log)

**Comment by karthikeyan5** [comment]
Have tried this: https://discuss.erpnext.com/t/how-to-integrate-biometric-device-in-erp-next-attendance/52252/18?u=karthikeyan5

**Comment by MdAlAmin-aol** [comment]
yes , i did. but no result.

**Comment by karthikeyan5** [comment]
@MdAlAmin-aol, you seem to be having an error which we have not seen before and there is insufficient information in the error log to conclude anything... The error logging has now been improved in the latest [commit](https://github.com/frappe/push-biometric-erpnext/commit/58d5dec30db254400e8fc5c0fa9bb78236366fca)... So, Please pull the latest changes and try again.. You would get a more detailed error log, which should help you solve the issue... 


Also, Next time you open an issue, Please paste the error in the Description instead of only uploading the file... this would help other people searching for a similar issue...
